question_data = [
    {"text": "The first video game ever created is considered to be 'Pong'.", "answer": "False"},
    {"text": "'The Legend of Zelda: Ocarina of Time' was the first 3D game in the Zelda series.", "answer": "True"},
    {"text": "The character Mario was originally called 'Jumpman' in 'Donkey Kong'.", "answer": "True"},
    {"text": "'Minecraft' was created by Markus Persson, also known as 'Notch'.", "answer": "True"},
    {"text": "In 'Pac-Man', the ghosts' movements are completely random.", "answer": "False"},
    {"text": "'Call of Duty' was first released in 2003.", "answer": "True"},
    {"text": "The longest-running video game franchise is 'Final Fantasy'.", "answer": "False"},
    {"text": "'The Sims' allows players to directly control the Sims' emotions.", "answer": "False"},
    {"text": "In 'Resident Evil', the main character Chris Redfield is a member of S.T.A.R.S.", "answer": "True"},
    {"text": "'World of Warcraft' launched in 2004.", "answer": "True"},
    {"text": "'Tetris' was created by a Russian game designer named Alexey Pajitnov.", "answer": "True"},
    {"text": "The voice actor for Nathan Drake in 'Uncharted' is Nolan North.", "answer": "True"},
    {"text": "'Final Fantasy VII' was the first game in the series to use 3D graphics.", "answer": "True"},
    {"text": "The Pokémon franchise was originally created by Nintendo.", "answer": "False"},
    {"text": "'Half-Life 3' has been officially released.", "answer": "False"},
    {"text": "The game 'E.T.' for the Atari 2600 is considered one of the worst video games of all time.", "answer": "True"},
    {"text": "In 'The Witcher 3', Geralt of Rivia has the ability to cast five different magical signs.", "answer": "True"},
    {"text": "The character Sonic the Hedgehog was created by SEGA to compete with Nintendo's Mario.", "answer": "True"},
    {"text": "'Halo: Combat Evolved' was originally designed to be a third-person shooter.", "answer": "True"},
    {"text": "In 'Fortnite', you can build structures to gain a tactical advantage.", "answer": "True"},
    {"text": "'Dark Souls' is known for its easy and beginner-friendly gameplay.", "answer": "False"},
    {"text": "The protagonist of 'BioShock' is named Booker DeWitt.", "answer": "False"},
    {"text": "In 'Skyrim', dragons were extinct before the events of the game began.", "answer": "True"},
    {"text": "'Grand Theft Auto V' features three main playable characters.", "answer": "True"},
    {"text": "In 'Overwatch', the character Tracer uses a bow and arrow as her main weapon.", "answer": "False"},
    {"text": "'Doom' is considered one of the pioneers of the first-person shooter genre.", "answer": "True"},
    {"text": "The video game 'Journey' has no dialogue, focusing entirely on visual storytelling.", "answer": "True"},
    {"text": "'Bloodborne' is a game developed by the same creators of 'Dark Souls'.", "answer": "True"},
    {"text": "In 'The Legend of Zelda: Breath of the Wild', Link has a voice actor for the first time in the series.", "answer": "False"},
    {"text": "'The Witcher' video game series is based on a series of novels by Andrzej Sapkowski.", "answer": "True"},
    {"text": "'Red Dead Redemption 2' is set in the 1800s American Wild West.", "answer": "True"},
    {"text": "The character 'Big Daddy' is a major antagonist in the 'Bioshock' series.", "answer": "True"},
    {"text": "'The Elder Scrolls V: Skyrim' was released in 2012.", "answer": "False"},
    {"text": "Master Chief is the protagonist of the 'Gears of War' series.", "answer": "False"},
    {"text": "The first video game with fully voiced dialogue was 'Baldur's Gate'.", "answer": "False"},
    {"text": "'Persona 5' is a role-playing game that features a group of high school students as the main protagonists.", "answer": "True"},
    {"text": "The Pokémon 'Pikachu' is known for its ability to control water.", "answer": "False"},
    {"text": "'Among Us' was released in 2020.", "answer": "False"},
    {"text": "'Cyberpunk 2077' takes place in the city of Night City.", "answer": "True"},
    {"text": "The original 'Diablo' game was developed by Blizzard Entertainment.", "answer": "True"},
    {"text": "In 'Super Smash Bros.', Sonic was introduced in the series' original release.", "answer": "False"},
    {"text": "Samus Aran is the protagonist of the 'Metroid' series.", "answer": "True"},
    {"text": "'Animal Crossing' features real-time gameplay based on the system's clock and calendar.", "answer": "True"},
    {"text": "The 'Metal Gear' series was created by Hideo Kojima.", "answer": "True"},
    {"text": "In 'Fallout', you can switch between first-person and third-person perspectives.", "answer": "True"},
    {"text": "'League of Legends' is a real-time strategy game.", "answer": "False"},
    {"text": "The 'Portal' series focuses heavily on the use of teleportation via portals.", "answer": "True"},
    {"text": "In 'The Last of Us', the virus is caused by a fungus called Cordyceps.", "answer": "True"},
    {"text": "'Street Fighter' was the first fighting game to feature character special moves.", "answer": "True"},
    {"text": "In 'Metal Gear Solid', Solid Snake is voiced by David Hayter in the original U.S. releases.", "answer": "True"},
    {"text": "'Minecraft' has sold over 200 million copies, making it the best-selling game of all time.", "answer": "True"},
    {"text": "'Kingdom Hearts' is a collaboration between Square Enix and SEGA.", "answer": "False"},
    {"text": "The character 'Kirby' was originally created to be a placeholder.", "answer": "True"},
    {"text": "The game 'Sekiro: Shadows Die Twice' features no multiplayer modes.", "answer": "True"},
    {"text": "The 'Silent Hill' series is known for its bright and cheery atmosphere.", "answer": "False"},
    {"text": "'Assassin's Creed' was originally going to be a Prince of Persia game.", "answer": "True"},
    {"text": "The character 'Tracer' in 'Overwatch' has the ability to rewind time.", "answer": "True"},
    {"text": "The Konami Code is used to unlock extra lives in 'Contra'.", "answer": "True"},
    {"text": "'EVE Online' is known for its player-driven economy and large-scale space battles.", "answer": "True"},
    {"text": "'Splatoon' is a competitive game that involves shooting ink at your opponents.", "answer": "True"},
    {"text": "In 'Final Fantasy X', Tidus is the main character.", "answer": "True"},
    {"text": "In 'League of Legends', the character Teemo is a jungler by default.", "answer": "False"},
    {"text": "'The Sims' allows players to build and manage the lives of simulated people.", "answer": "True"},
    {"text": "The main character of 'The Last of Us Part II' is Ellie.", "answer": "True"},
    {"text": "'Monster Hunter' is a game series that involves fighting and capturing large creatures.", "answer": "True"},
]
